### ISSUE TITLE
missing variable column in data datataframe for ICOS ATC NRT Meteo growing time series

### ISSUE THREAD

**Issue by KarolinaPntzt** [ICOS-Carbon-Portal/jupyter-archive#18]
Even though the variable 'Air Pressure (AP)' appears in the list of available variables for the data object described by the following parameters:

Data product: ICOS ATC NRT Meteo growing time series
Station: Hohenpeissenberg
Sampling height: 50.0
Variable: Air Pressure (AP)

When .get() is called, the column "AP" is completely missing from the returning dataframe.

**Comment by claudiodonofrio** [comment]
Tabular data specification defines all possible columns, but a station is allowed to submit a subset.
Further even if a 'column' is submitted it is possible that it contains no valid data.
The column names of the data object provide always the correct names for the submitted file.
Hence, for the moment, the user needs to check if a column contains valid data points.  
As a possible enhancement, i will look into an added information field for each column, to check if datapoints are available.

**Comment by claudiodonofrio** [comment]
looking further into a possible solution. it is not feasible to add this enhancement, without rewriting the library. At the moment the actual data gets only pulled by invoking the .get() command. Hence it is impossible to know if a column has valid data points after creating the Dobj() instance.
The easiest way at the moment will be to check if a column has a count of 0 or more after getting the data for a specific pid.

> data = Dobj(...).get()
> for columns in data:
>    print(columns, data[columns].count())

**Comment by claudiodonofrio** [comment]
on the html landing page of each data object all possible variables are listed and it is consistent to the results in the library.
