### ISSUE TITLE
station class: labeled ICOS station with data in Drought2018 return null in station.getList(['as'])[i].products()

### ISSUE THREAD

**Issue by KarolinaPntzt** [ICOS-Carbon-Portal/jupyter-archive#19]
The following labeled ICOS stations that have provided datasets for "Drought 2018 Atmospheric Product", return null in:
`station.getList(['as'])[i].products()`

- Birkenes Observatory
- Cabauw
- Lampedusa
- Plateau Rosa Station
- Puijo
- Ridge Hill
- Saclay
- Schauinsland
- Weybourne

**Comment by claudiodonofrio** [comment]
resolved with release 0.1.0. Station logic is now reversed....base is the dataportal and additional informatino is pulled from the labelling app.
But be aware that station.getList(['as']) returns icos stations. Hence it is possible that not all Drought stations are returned. Hence we need to cycle through all ids (getIdList('all') and extract the data products and filter for Drought.....
