### ISSUE TITLE
Wishlist for updating the docker image

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/jupyter-archive#191]
python modules:
- [x] `zarr`
- [x] `plotly`
- [x] `pygmt`
  - [x] `gmt` conda dependency for `pygmt`
  - [x] `/home/user/.gmt` jupyter directory must belong to the user for `pygmt` to work correctly.

other tools:

- [x] `nco` http://nco.sourceforge.net/

**Comment by ZogopZ** [comment]
Closed and continued in #160.
