### ISSUE TITLE
station characterization for non-ICOS stations

### ISSUE THREAD

**Issue by ukarst** [ICOS-Carbon-Portal/jupyter-archive#215]
For non-ICOS stations
-  error writing settings.json in line `del settings_copy['icos']`
- comments are printed on the screen, see screen shot
<img width="1003" alt="Screenshot 2022-07-26 at 15 27 08" src="https://user-images.githubusercontent.com/2862831/181017643-09022372-e724-4ff6-9f4f-ef55d586aa0c.png"

**Comment by idastorm** [comment]
In the commit where I attempt a commit that solves this (like above) the reference stations are still listed.
![image](https://user-images.githubusercontent.com/31061856/181038235-1be33f5e-360a-4780-b7f5-6691ef6ad5a6.png)

@ukarst had suggested that "Maybe the comment can be reduced to one line with the information that not all stations are available for comparison in this particular year."  This was just to show a second option but I agree that maybe such a statement might be enough.
