### ISSUE TITLE
Ecosystem Anomalies 

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/jupyter-archive#324]
The notebook for Ecosystem Anomalies, highlighted in the announcement text should be added to the index notebook for easy access.
(https://exploredata.icos-cp.eu/hub/user-redirect/lab/tree/icos_jupyter_notebooks/ecosystem_site_anomaly_visualization.ipynb)

**Comment by ZogopZ** [comment]
Closed via #352
