### ISSUE TITLE
Station Chararcterization seasonal table not created error

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/jupyter-archive#73]
selecting station with followint settings creates error:
{
    "stationCode": "SMR127",
    "startYear": 2007,
    "startMonth": 1,
    "startDay": 1,
    "endYear": 2007,
    "endMonth": 1,
    "endDay": 8,
    "timeOfDay": [
        0,
        3,
        6,
        9,
        12,
        15,
        18,
        21
    ],
    "binSize": 15,
    "binInterval": 100,
    "unit": "percent",
    "titles": "",
    "labelPolar": "yes",
    "saveFigs": "yes",
    "icos": {
        "stationId": "SMR",
        "name": "Hyyti\u00e4l\u00e4",
        "theme": "AS",
        "icosclass": "1",
        "siteType": "Tall tower",
        "lat": 61.8474,
        "lon": 24.2947,
        "eas": 181.0,
        "eag": "127",
        "firstName": "Ivan",
        "lastName": "Mammarella",
        "email": "ivan.mammarella@helsinki.fi",
        "country": "FI",
        "project": [
            "ICOS"
        ],
        "uri": [
            "http://meta.icos-cp.eu/resources/stations/AS_SMR"
        ]
    },
    "stilt": {
        "lat": 61.85,
        "lon": 24.29,
        "alt": 127,
        "locIdent": "61.85Nx024.29Ex00127",
        "id": "SMR127",
        "name": "SMEAR/Hyyti\u00e4l\u00e4 127m",
        "icos": true,
        "years": [
            "2006",
            "2007"
        ],
        "2006": {
            "months": [
                "01",
                "cache180_4096.txt"
            ],
            "nmonths": 2
        },
        "2007": {
            "months": [
                "01",
                "09",
                "12",
                "07",
                "06",
                "02",
                "10",
                "03",
                "08",
                "04",
                "05",
                "11",
                "cache180_4096.txt"
            ],
            "nmonths": 13
        }
    },
    "figFormat": "png",
    "date/time generated": "20210325_133256_",
    "output_folder": "output/20210325_133256_SMR127",
    "Sensitivity": "fourth quartile",
    "Population": "third quartile",
    "Point source": "fourth quartile"
}

**Comment by claudiodonofrio** [comment]
This is the errormessage
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/icos_jupyter_notebooks/station_characterization/gui.py in update_func(button_c)
    321     with result_seasonal_table:
    322         result_seasonal_table.clear_output()
--> 323         fig, caption=stc_functions.seasonal_table(stc)
    324         stc.add_figure(5, fig, caption)
    325         display(HTML('<p style="font-size:16px">'  + caption + ' </p>'))

~/icos_jupyter_notebooks/station_characterization/stc_functions.py in seasonal_table(myStation)
    895 
    896         if year_before in years:
--> 897             months_year_before = available_STILT[year_before]['months']
    898         else:
    899             months_year_before=''

KeyError: 2006

**Comment by idastorm** [comment]
Fixed with branch #97
