### ISSUE TITLE
icos_atmObs_statistics.ipynb

### ISSUE THREAD

**Issue by claudiodonofrio** [ICOS-Carbon-Portal/jupyter-archive#82]
we need store the maps for the footprint visualisation in the docker image. otherwise each time the notebook is called, all the maps are downloaded again.

**Comment by KarolinaPntzt** [comment]
I think you are referring to "icos_atmObs_STILT .ipynb". 
icos_atmObs_statistics.ipynb does not have any cartopy maps that require basemap data from Natural Earth.
